apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: scenario1-default
  labels:
    app: enmasse
spec:
  version: 0.26-SNAPSHOT
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 5Gi
      storage: 50Gi
    addressFullPolicy: FAIL
  router:
    minReplicas: 1
    resources:
      memory: 512Mi
    linkCapacity: 250
