apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: online.client-1
spec:
  username: client-1
  authentication:
    type: password
    password: Y2xpZW50LTEtcGFzc3dvcmQ=
  authorization:
    - addresses: ["input"]
      operations: ["send"]
