apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: results.client-1
spec:
  username: client-1
  authentication:
    type: password
    password: Y2xpZW50LTEtcGFzc3dvcmQ=
  authorization:
    - addresses: ["results-client.1", "alert"]
      operations: ["recv"]
