apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: results.client-2
spec:
  username: client-2
  authentication:
    type: password
    password: Y2xpZW50LTItcGFzc3dvcmQ=
  authorization:
    - addresses: ["results-client.2", "alert"]
      operations: [ "recv"]
