apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: batch.input.client-2
spec:
  username: client-2
  authentication:
    type: password
    password: Y2xpZW50LTItcGFzc3dvcmQ=
  authorization:
    - addresses: ["input"]
      operations: [ "send"]
