apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: results.processor-user
spec:
  username: processor-user
  authentication:
    type: password
    password: cHJvY2Vzc29yLXVzZXItcGFzc3dvcmQ= 	      
  authorization:
    - addresses: ["results-client.*"]
      operations: ["send"]


