apiVersion: admin.enmasse.io/v1beta1
kind: AddressPlan
metadata:
  name: online-queue
  labels:
    app: enmasse
displayName: Online Queue
displayOrder: 0
shortDescription: Creates a small queue sharing underlying broker with other queues.
longDescription: Creates a small queue sharing underlying broker with other queues.
uuid: 0843743a-0503-11e8-91df-507b9def37da
addressType: queue
requiredResources:
- name: router
  credit: 0.0001
- name: broker
  credit: 0.0001

